### ISSUE TITLE
2FA incompatibility with Magento 2.4.4

### ISSUE THREAD

**Issue by Silarn** [Kount/magento2-kount#10]
It appears the version of the endroid/qr-code package was updated to ^4.3.5 with Magento 2.4.4.

This has caused the 2FA support in the Kount module to break, as the method for defining the QR Code settings was changed. (It now uses the Endroid\QrCode\Builder\Builder class to create, define settings, and build the final QR code.)

Additionally, since the form in the customer account does not include a form key element and the Controller classes do not implement the CsrfAwareActionInterface, the form submission fails because no form key was submitted with the 2FA code which fails to validate with the default CSRF validator.

**Comment by Silarn** [comment]
This was fixed with 4.3.9, however it might be good to define the endroid requirement since upgrading will break Magento 2.4.3 installs.

**Comment by Alexander-Pop** [comment]
Looks like related 
Kount 2.4.9, Magento 2.4.3-p2 - on login page got :
Error: Call to undefined method Endroid\QrCode\QrCode::setData() in /Users/sasha/DEV/SITES/Nutrafol/nutrafol-nutrafol_staging/vendor/kount/magento2-kount/src/module-kount-2fa/Model/GoogleAuthenticatorService.php:35
