### ISSUE TITLE
Incompatible 4.3.5 with kount/kount-ris-php-sdk 7.4.0

### ISSUE THREAD

**Issue by advocat** [Kount/magento2-kount#8]
**Precondition:**
- Install version "kount/magento2-kount": "^4.3" into Magento 2.4.x
- Install "kount/kount-ris-php-sdk": "7.4.0" by dependency

**How to replicate:**
- Configure Kount extension
- Try to place order using any applicable payment method

**Actual Result:**
- Error `Undefined index: VERS in vendor/kount/kount-ris-php-sdk/src/Kount/Ris/ArraySettings.php on line 120`

**Comment by Silarn** [comment]
Yes, I ran into this after an update last night unexpectedly. I suppose I should have tested with Kount enabled. As long as you restrict the kount/kount-ris-php-sdk to <7.4.0 you'll be fine.

The Magento module code will need to be updated to include this value in the config options.

**Comment by dharp-kount** [comment]
kount/kount-ris-php-sdk 7.4.1 has been released and should resolve this issue.
